name: stripe_example
description: Demonstrates how to use the stripe plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^6.0.0
  flutter_stripe_web: ^2.0.0
  stripe_checkout: ^1.0.0
  pay: ^1.0.11
  http: ^0.13.5
  font_awesome_flutter: ^10.2.1
  platform: ^3.1.0
  url_launcher: ^6.1.6
  flutter_svg: ^1.1.6


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/Tica_0222.png
    - assets/images/Asset131.png
    - assets/images/Image1.png
    - assets/images/bg.svg

  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: fonts/OtomanopeeOne.ttf
